### ISSUE TITLE
Adding license?

### ISSUE THREAD

**Issue by hr-oss** [joecamp/BlasteroidsPublic#1]
Howdy!

Love this game :) Was curious, if you’d like to add a license to the repo, so people don’t have to worry about getting sued if they use it? 😆

Here’s a tutorial on how to add one: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you!

**Comment by joecamp** [comment]
Thank you for the suggestion! I've added a license to the repository.
